[COMMON]
PROJECT_NAME = ingest-agent
PROJECT_VERSION = 0.1.1
THREAD_COUNT = 3
META_SCHEMA_URL = https://github.com/oncocross/datalake-catalog/blob/schemas/metadata/1.1.0.schema.json
REGION_NAME = ap-northeast-2
S3_BASE_PATH = ingest-agent

[ACQUISITION]
SOFTWARE_NAME = xcalibur
SOFTWARE_VERSION = 4.3
MODE_CODE = DIA
MODE_URL = http://purl.obolibrary.org/obo/MS_1003221

[DEV]
COGNITO_USER_POOL_ID = ap-northeast-2_q01VQBvJP
AWS_DB_SECRET_ID = arn:aws:secretsmanager:ap-northeast-2:142644586660:secret:oncx-dev-common-db-secret-root-GPbnlw
DB_SSM_TUNNEL_PORT = 15432
S3_BUCKET = oncx-dev-data-datalake-bucket-bronze
STATE_MACHINE_ARN = arn:aws:states:ap-northeast-2:142644586660:stateMachine:oncx-dev-platform-workflow-sm-datalake

[PRD]
COGNITO_USER_POOL_ID = ap-northeast-2_mGIovnxid
AWS_DB_SECRET_ID = arn:aws:secretsmanager:ap-northeast-2:142644586660:secret:oncx-prd-common-db-secret-root-4Aog96
DB_SSM_TUNNEL_PORT = 25432
S3_BUCKET = oncx-prd-data-datalake-bucket-bronze
STATE_MACHINE_ARN = arn:aws:states:ap-northeast-2:142644586660:stateMachine:oncx-prd-platform-workflow-sm-datalake
