[COMMON]
PROJECT_NAME = ingest-agent
THREAD_COUNT = 7
META_SCHEMA_URL = https://example.com/datalake-catalog/metadata/1.2.0.schema.json
REGION_NAME = ap-northeast-2
S3_SOURCE = ingest_agent

[ACQUISITION]
SOFTWARE_NAME = xcalibur
SOFTWARE_VERSION = 4.3
MODE_CODE = DIA
MODE_URL = http://purl.obolibrary.org/obo/MS_1003221

[DEV]
COGNITO_USER_POOL_ID = ap-northeast-2_q01VQBvJP
S3_BUCKET = oncx-dev-data-datalake-bucket-bronze
STATE_MACHINE_ARN = arn:aws:states:ap-northeast-2:142644586660:stateMachine:oncx-dev-platform-workflow-sm-datalake
API_SERVER_BASE_URL = https://10sa8a2lk5.execute-api.ap-northeast-2.amazonaws.com/api-server/v1
# self-update 채널 (CloudFront, aws-iac envs/dev/app_update_cdn)
UPDATE_BASE_URL = https://d1bhbnqc9n96eq.cloudfront.net/ingest-agent

[PRD]
COGNITO_USER_POOL_ID = ap-northeast-2_mGIovnxid
S3_BUCKET = oncx-prd-data-datalake-bucket-bronze
STATE_MACHINE_ARN = arn:aws:states:ap-northeast-2:142644586660:stateMachine:oncx-prd-platform-workflow-sm-datalake
API_SERVER_BASE_URL = https://iupsj9zxsa.execute-api.ap-northeast-2.amazonaws.com/api-server/v1
# self-update 채널 (CloudFront, aws-iac envs/prd/app_update_cdn)
UPDATE_BASE_URL = https://d3ef54ca45p8pl.cloudfront.net/ingest-agent
